---
title: "meteorites"
author: "James Adams"
date: "17/06/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(maps)
```

```{r}
meteorites <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-11/meteorites.csv")
```

```{r}
ukFalls <- meteorites %>% 
  filter(lat >= 50 & lat <= 60 & long <= 2 & long >= -11) %>% 
  filter(!name %in% c("Limerick", "Dundrum", "Mooresfort", "Leighlinbridge", "Pettiswood")) %>%
  mutate(massKG = mass/1000) %>% 
  mutate(nameYear = paste(name, year, sep = ", ")) %>% 
  arrange(year)

ukMap <- map_data(regions = "uk", map = "world") %>% filter(lat <=58.73)

ggplot(ukMap, aes(x = long, y = lat)) + 
  geom_polygon(aes(group = group), colour = "black", fill = "#222831") +
  geom_point(data = ukFalls, aes(x = long, y = lat, size = massKG), colour = "#d65a31") +
  geom_text(data = subset(ukFalls, massKG >=10), aes(label = nameYear), hjust = 0, nudge_x = 0.2, size = 3) +
  scale_size(range = c(0, 5), breaks = c(5,15,25,50), labels = c("5 kg", "15 kg", "25 kg", "50 kg")) +
  theme_void() +
  theme(plot.background = element_rect(fill = "#5588a3"),
        plot.margin = margin(.5, .5, .5, .5, "cm")) +
  labs(size = "Mass",
       alpha = "Mass")

ggsave("map.pdf")
```
